### ISSUE TITLE
Use of unresolved identifier 'HUD'

### ISSUE THREAD

**Issue by alexandergmacleod** [pkluz/PKHUD#103]
My project fails when building using one of the example functions on my view controller with the reason:

> Use of unresolved identifier 'HUD'

```
import PKHUD

class SomeViewController: UIViewController {
    override func viewDidLoad() {
        HUD.flash(.Success, delay: 1.0) { finished in
            // Completion Handler
        }
    }
}
```

Could anyone help? Thanks

**Comment by PGLongo** [comment]
How you have included the library? And which version?
