### ISSUE TITLE
How to use PKHUD swift 3.0

### ISSUE THREAD

**Issue by dromerobarria** [pkluz/PKHUD#104]
Any chance a new update for swift 3.0

**Comment by justdan0227** [comment]
Anyone?

**Comment by Dark0rion** [comment]
update to swift 3 please!

**Comment by j0sem4rio** [comment]
3.0 pls

**Comment by bagwanshoaib** [comment]
3.0???

**Comment by alexandergmacleod** [comment]
I've managed to get it working using Swift 3 Xcode 8. Using CocoaPods, you need to add the following to your PodFile:

`pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'`

`post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end`

Hope this helps!

**Comment by sabiland** [comment]
@alexandergmacleod great! :)

**Comment by j0sem4rio** [comment]
:10:8: Module file was created by an older version of the compiler; rebuild 'PKHUD' and try again: /iphoneos/PKHUD.framework/Modules/PKHUD.swiftmodule/arm64.swiftmodule
anybody help me

**Comment by Unsan** [comment]
@j0sem4rio  try   rm -rf ~/Library/Developer/Xcode/DerivedData

**Comment by j0sem4rio** [comment]
@Unsan work!!! thanks

**Comment by esetnik** [comment]
@pkluz can you open an official swift 3 branch please?

**Comment by embassem** [comment]
support swift 3 and carthage

**Comment by coanag** [comment]
Recently trying to get it with carthage, but I'm getting:
*** Building scheme "PKHUD" in PKHUD.xcodeproj
** BUILD FAILED **
In cart file i use: gitHub "pkluz/PKHUD"
I user Xcode 8
Any recommendations?

**Comment by esetnik** [comment]
@coanag you can use the toyship/PKHUD fork `github "toyship/PKHUD" "master"`

**Comment by coanag** [comment]
@esetnik And another.. is it possible for Swift 2.3?

**Comment by esetnik** [comment]
Swift 2.3 should be a relatively easy fix, just fork the project, compile it with xcode 8 (run the auto migration) and then point carthage at your own fork.

**Comment by pkluz** [comment]
Resolved via `43e3ad`
