### ISSUE TITLE
Warning-Message at .LabeldError

### ISSUE THREAD

**Issue by PetresS** [pkluz/PKHUD#106]
Hey, 

i'm using this pod and everything works fine for me.
The only thing that attracted my attention is a "warning" in my console.

before a request i call HUD.show(.Progress) and if my request failed i call
HUD.flash(.LabeledError(title: nil, subtitle: response.msg), delay: 2.0)

and my console shows me this:
>  PKHUD.FrameView 0x7fc342058a60 is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

But I'm not sure if the issue is on my side.

**Comment by PGLongo** [comment]
Don't worry it's not your fault. There is already a discussion for that. Please see #6
