### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by portwatcher** [pkluz/PKHUD#110]
We have a big app so that we can't migrate to Swift3 immediately. I've found some nice prs that support Swift3 but no Swift2.3 pr.

Any plan for this?

**Comment by wieweb** [comment]
I'm using [https://github.com/jing-y/PKHUD](https://github.com/jing-y/PKHUD)
There is a swift 2.3 branch.

**Comment by portwatcher** [comment]
Thanks for bringing this useful message.
