### ISSUE TITLE
How can i add text to HUD Progress icon?

### ISSUE THREAD

**Issue by martinepedro** [pkluz/PKHUD#111]
Is it possible to add a text right in the bottom of .Progress or any other HUDContentType at HUD class?
Thank you!

**Comment by fraserscottmorrison** [comment]
Id like this too. I also tried to create a new processView with a custom spinner. Unfortunately, its very difficult to extend

**Comment by PGLongo** [comment]
Actually the .progress looks like this

![simulator screen shot 27 oct 2016 18 29 42](https://cloud.githubusercontent.com/assets/3647884/19776186/62b7d676-9c73-11e6-9de8-5f196e87e3ca.png)

But if you want you can easily change the alignment of the text:

```swift
let hud = PKHUDProgressView(title: "title", subtitle: "subtitle")
        hud.subtitleLabel.textAlignment = .right
        PKHUD.sharedHUD.contentView = hud
        PKHUD.sharedHUD.show()
        
```
![simulator screen shot 27 oct 2016 18 33 47](https://cloud.githubusercontent.com/assets/3647884/19776351/f4fcd950-9c73-11e6-8a50-9388eaafdb3b.png)

Is this fine for you?
