### ISSUE TITLE
Resize HUD dynamically based on width of sub/title

### ISSUE THREAD

**Issue by domhof** [pkluz/PKHUD#117]
I'm using PKHUDProgressView as contentView for the HUD and I would like to resize it based on the width of the subtitle. If I set subtitleLabel.adjustsFontSizeToFitWidth = false and update the frame of the contentView when the subtitle text changes, the contentView resizes correctly but the frame of the FrameView remains the same. Is there a way to trigger an update of the Window/FrameView when the frame of the contentView changes?

**Comment by PGLongo** [comment]
PKHUD don't use autolayout so at the moment is not possibile. I will discuss with @pkluz about your request.

Temporarily if you want you can easily create your own PKHUDProgressView in this way

```swift

class domhofHUDProgressView : PKHUDProgressView{
    open override func layoutSubviews() {
        super.layoutSubviews()
        
        let viewWidth = bounds.size.width
        let viewHeight = bounds.size.height
        
        titleLabel.frame = CGRect(origin: CGPoint.zero, size: CGSize(width: viewWidth, height: titleHeight))
        imageView.frame = CGRect(origin: CGPoint(x:0.0, y:quarterHeight), size: CGSize(width: viewWidth, height: imagefHeight))
        subtitleLabel.frame = CGRect(origin: CGPoint(x:0.0, y:threeQuarterHeight), size: CGSize(width: viewWidth, height: subTitleHeight))
    }
}
```

**Comment by domhof** [comment]
Thanks for the detailed answer @PGLongo

**Comment by PGLongo** [comment]
You are welcome.
