### ISSUE TITLE
I can't install the framework? Import error: "No such module PKHUD"

### ISSUE THREAD

**Issue by ghost** [pkluz/PKHUD#12]
Hi, 

the framework looks so awesome. 
But I have problems to use it: 

I downloaded the newest .zip from 04/12/2014. 
Unzip the files. 
Drag & Drop the folder "PKHUD" to my existing swift xcode project. 
Then I go to my "AppDelegate.swift" and adding on the top, right under the "import UIKIT" a new line: 
import PKHUD

The compiler show me an error: "No such module PKHUD". 
What do I wrong? 

[By the way the standalone Demo-versions works perfect. I think I have just a little problem, to import the PKHUD.]

I'm using the new Xcode 6.1.1 from the Mac App Store, no beta.
And OS X 10.10.1 Yosemite.

**Comment by ashumishra224** [comment]
you are right ghost. I have also solved my problem. Thank you
