### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by demonar** [pkluz/PKHUD#124]
I created a branch from the label 3.2.1, the only changes are target related and labeled 3.2.2, if you want we could move that to a branch in the master repo and leave it as a swoft 2.3 version.

**Comment by PGLongo** [comment]
If you are interested make a PR on that branch so I can consider it

**Comment by demonar** [comment]
the thing is that is a new branch, i can't create a pull request from a branch to the original repo, here's the link to the tree in my fork: https://github.com/demonar/PKHUD/tree/swift2.3

Have a look and, if you like, you can create the branch swift2.3 on the original repo so i can create the PR.

Remember that the point in history is the label 3.2.1

**Comment by PGLongo** [comment]
Done with #128

**Comment by PGLongo** [comment]
Thanks @demonar

**Comment by demonar** [comment]
@PGLongo i think the last thing would be to add the 3.2.2 tag to that branch, that way it will be visible in the versions history

**Comment by PGLongo** [comment]
Ok, done. Remember to specify the tag or the branch using CocoaPods.

pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git, : tag => '3.2.2'
pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git, :branch => 'swift-2.3'
