### ISSUE TITLE
Changing the root view controller of window breaks the hud

### ISSUE THREAD

**Issue by jordancamara** [pkluz/PKHUD#126]
After I change the root view controller of the application's window, trying to pop up the HUD fails and nothing happens. Any ideas?

**Comment by PGLongo** [comment]
You should hide the hud and then in the completion handler change the view controller. You are welcome but please next time use [StackOverflow](https://github.com/pkluz/PKHUD#communication-hat-tip-alamofire) as written in the README. 

Thanks
