### ISSUE TITLE
Dismiss When Tapped

### ISSUE THREAD

**Issue by lazar89nis** [pkluz/PKHUD#127]
Great library. I will start using it in my swift projects. Is there a way to add dismiss when tapped action?

**Comment by PGLongo** [comment]
Hi @lazar89nis, it's not in the aim of this library to be dismissed when tapped so I don't think nobody will add this feature very soon. 

By the way you can achieve that adding a tap gesture recognizer on the HUD view and then hide the HUD when the callback is fired.

**Comment by PGLongo** [comment]
You are welcome but please next time use StackOverflow as written in the README.

Thanks
