### ISSUE TITLE
Hud Resize

### ISSUE THREAD

**Issue by PGLongo** [pkluz/PKHUD#130]
A new feature very requested is the capability of changing the size of the HUD.

Maybe we could add a constant file, for instance the size of PKHUDSquareBaseView is 156x156 so we would have:

```swift
enum PKHUDSize {
  static let PKHUDSquareBaseViewWidth = 156.0
  static let PKHUDSquareBaseViewHeight = 156.0
// or even better     static let PKHUDSquareBaseViewSize = CGSize(width: 156.0, height: 156.0)

}
```

So
```swift
static let defaultSquareBaseViewFrame = CGRect(origin: CGPoint.zero, size: CGSize(width: 156.0, height: 156.0))
```

So
```swift
static let defaultSquareBaseViewFrame = CGRect(origin: CGPoint.zero, size: CGSize(width: 156.0, height: 156.0))
....
 public init(image: UIImage? = nil, title: String? = nil, subtitle: String? = nil) {
        super.init(frame: PKHUDSquareBaseView.defaultSquareBaseViewFrame)
        ...
    }
```

Became

```swift
156.0))
 public init(image: UIImage? = nil, title: String? = nil, subtitle: String? = nil) {
        let frame = CGRect(origin: CGPoint.zero, size: CGSize(width: PKHUDSize.PKHUDSquareBaseViewWidth, height: PKHUDSize.PKHUDSquareBaseViewHeight)
        super.init(frame: frame)
        ...
    }
```

**Comment by PGLongo** [comment]
I hope to read the opinion of @pkluz, @cody1024d or every one who has interest in this feature

**Comment by cody1024d** [comment]
@PGLongo 

I think this is good.  The only thing I'm not seeing (because of scoping, maybe) is where the user-configuration of size would come in?  In my opinion, it would be best to do this through a constructor; something as simple as:

```swift
public init(image: UIImage? = nil, title: String? = nil, subtitle: String? = nil, size: CGSize = CGSize(width: 156.0, height: 156.0)) {
        let frame = CGRect(origin: CGPoint.zero, size: size)
        super.init(frame: frame)
        ...
    }
```

I think that works.  However; I think only using a default parameter on the constructor *may* not be as clear as to where the default width/height is coming from.  I still think, though, that adding the parameter in the constructor is the way I would go to allow the user to specify the size they want.  Thoughts?

**Comment by PGLongo** [comment]
@cody1024d I was thinking in a more easy and reusable way, you change the size once and then every HUD will be resized:

In AppDelegate 
```swift
PKHUDSize.PKHUDSquareBaseViewSize = CGSize(width: 200, height: 200)
```

Then in your code you can call
```swift
HUD.flash(.Success, delay: 1.0)
//instead of HUD.flash(.Success, delay: 1.0, size: CGSize(width: 200, height: 200))
```

**Comment by cody1024d** [comment]
@PGLongo  Ahhh, yeah, that does make sense.  There's probably never really a use-case to have different sized progress dialogs throughout the application, at least I can't really think of one off the top of my head.

**Comment by kamirana4** [comment]
This size configuration is really much needed element right now. And i think a configuration struct/class (e.g, HUDConfig) should be added that needs to be configured in the AppDelegate. Like below,

```
public struct HUDConfig {

let font: UIFont
let titleColor: UIColor
let size: CGSize

public init(font: UIFont = UIFont.systemFont(ofSize: 14), titleColor: UIColor = .black, size: CGSize = CGSize(width: 156, height: 156) {
    self.font = font
    self.titleColor = titleColor
    self.size = size
  }
}

In HUD.swift
public static var config: HUDConfig

In AppDelegate.swift
let hudConfig = HUDConfig(font: somefont, titleColor: somecolor, size: anySize)
HUD.config = hudConfig
```

I think this will give better control to add more options in the future.

**Comment by PGLongo** [comment]
Thanks @kamirana4 but there are too many possible configurations and so it would be very hard to change the behaviour using a struct with a init. I prefer a struct with static fields.

I like the name **HUDConfig**

**Comment by PGLongo** [comment]
@pkluz what do you think?

**Comment by CaliosD** [comment]
I wonder what this issue's status is. I've also come across the same problem. Hoping to see it.

**Comment by PGLongo** [comment]
This issue is very important, but nobody is working on it right now. Sorry

**Comment by PGLongo** [comment]
Move discussion to #157
