### ISSUE TITLE
Stops working and crashes app when deployed to App Store

### ISSUE THREAD

**Issue by amajeedmuazu** [pkluz/PKHUD#131]
Very strange problem,

The code/plugin works fine when testing via Xcode, however when I submit the app to the AppStore for TestFlight installation, the plugin doesn't work and crashes the app.

What could be going on?

**Comment by PGLongo** [comment]
Have you any log?

Try to submit the app including bitcode

**Comment by PGLongo** [comment]
@amajeedmuazu have you fixed it? In few days I will consider this issue as closed.

**Comment by PGLongo** [comment]
I've released an app on the store with PKHUD included and everything is fine
