### ISSUE TITLE
No issue, just thanks!

### ISSUE THREAD

**Issue by TotemChris** [pkluz/PKHUD#136]
Thanks for keeping this repo up to date.  It adds really great polish to my app, and its super simple to implement.  Thanks again @pkluz !

**Comment by PGLongo** [comment]
Hi @TotemChris, I'm happy that you like the project, but please don't open issue for that.

**Comment by pkluz** [comment]
Also please note that the most recent stream of maintenance is thanks to @PGLongo who's been doing a fantastic job!

**Comment by PGLongo** [comment]
We are trying Slack. @TotemChris if you want to discuss with us please give me your email and I will add you.
