### ISSUE TITLE
Please update specs and sample code for Swift 3

### ISSUE THREAD

**Issue by nikans** [pkluz/PKHUD#140]

**Comment by PGLongo** [comment]
Tomorrow I will update the README. 

What is wrong with the specs?

**Comment by PGLongo** [comment]
@nikans can you tell me what is the problem?

I've updated the readme

**Comment by nikans** [comment]
Well as far as I see, the only problem has been with enum cases )

**Comment by PGLongo** [comment]
Ok thanks
