### ISSUE TITLE
Add the gesture support

### ISSUE THREAD

**Issue by a5978445** [pkluz/PKHUD#143]
The code is as follows:
    HUD.show(.labeledImage(image: nil, title: "test", subtitle: "hello world"))
            
    PKHUD.sharedHUD.contentView .addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(MyTableViewController.test)))

I want users to click on the screen, manually hide the hud, but i cant's get the maskView point,I don't have permission to access “container”  property

**Comment by PGLongo** [comment]
Sorry but I don't think this is necessary.
