### ISSUE TITLE
PKHUD memory leaks , help wanted

### ISSUE THREAD

**Issue by lifanhaha** [pkluz/PKHUD#146]
![2017-03-08 10 08 19](https://cloud.githubusercontent.com/assets/13114273/23686942/3b17b97a-03e7-11e7-985a-00ae61be00cd.png)

**Comment by lifanhaha** [comment]
![2017-03-08 10 13 55](https://cloud.githubusercontent.com/assets/13114273/23687114/ff776bb2-03e7-11e7-8a5a-8f3583d428df.png)

**Comment by lifanhaha** [comment]
@pardel @angerman @feinstruktur @hebertialmeida @diejmon

**Comment by PGLongo** [comment]
Hi @lifanhaha, sorry for the delay. Can you check with the last version and with the demo project?

I've try right now and I haven't found  any leak

**Comment by lifanhaha** [comment]
Thank you, have been solved, it is caused by other
