### ISSUE TITLE
xcode 8.3 swift 3 warnings

### ISSUE THREAD

**Issue by Alexookah** [pkluz/PKHUD#152]
@pkluz 
there are some warnings in the latest xcode 8.3

PKHUDAnimation.swift:19:41: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

`            NSNumber(value: 1.0 * Float(M_PI) / 6.0 as Float),
`

**Comment by LaurentiuUngur** [comment]
Duplicated. Please see https://github.com/pkluz/PKHUD/issues/149

**Comment by mikestalker** [comment]
I'm sorry, maybe i do something wrong, but i do "pod update PKHUD --verbose", uninstall and reinstall cocoapods, PKHUD pod, but any way i do not get these fixes and still have these M_PI. I understand that can manually change source code, but want to resolve it in right way. What should i do to get finally these changes in my project?

**Comment by LaurentiuUngur** [comment]
It should be released a new version to fix that warnings

**Comment by mikestalker** [comment]
@pkluz can you do it?

**Comment by PGLongo** [comment]
Merged

**Comment by PGLongo** [comment]
For now use the master version for these changes

**Comment by mikestalker** [comment]
@pkluz thanks, but it not helped. `pod update PKHUD` still do not get these changes )=

**Comment by PGLongo** [comment]
@mikestalker as I said before, for now [specify master version in your podfile](https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo).

`pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git'`

**Comment by mikestalker** [comment]
Oh. Got it. Thank you.

**Comment by PGLongo** [comment]
@mikestalker I've release a new pod version. For more details have a look to #150

**Comment by mikestalker** [comment]
@PGLongo thank you (=
