### ISSUE TITLE
Error generated when PKHUD used in the extension

### ISSUE THREAD

**Issue by ramunasjurgilas** [pkluz/PKHUD#158]
PKHUD can not be used without modification in the iOS extensions. It gives this error:
**_User/Frameworks/PKHUD/PKHUD.swift:100:69: 'shared' is unavailable: Use view controller based solutions where appropriate instead._**

**Comment by PGLongo** [comment]
Duplicated of #122

**Comment by ramunasjurgilas** [comment]
I did forgot that it was opened by me some months ago.
