### ISSUE TITLE
Unwind seque but HUD showing

### ISSUE THREAD

**Issue by danlniel** [pkluz/PKHUD#159]
I try showing HUD in modal presentation and then hide HUD,
but then when i try to unwind back to first View Controller
the HUD is showing and active in View Controller target 
Thank you.

**Comment by PGLongo** [comment]
Hi @danlniel, please next time use StackOverflow as written in the [README](https://github.com/pkluz/PKHUD#communication-hat-tip-alamofire). 

Please add some code here or on StackOverflow if you want some help

**Comment by PGLongo** [comment]
Have you found a solution?
