### ISSUE TITLE
Crashes on HUD.show() in very first VC

### ISSUE THREAD

**Issue by Blackjacx** [pkluz/PKHUD#162]
Hey,

when I call `HUD.show()` in the very first view controller the app crashes because you explicitly unwrap `UIApplication.shared.keyWindow` in the method `show(onView view: UIView? = nil)`. At this time this window is nil but `UIApplication.shared.delegate.window` is not ;-) 

Maybe you can change that?

**Comment by kmcgill88** [comment]
I just ran into this as well. I added my VC's view and now it worked `HUD.show(.systemActivity, onView: self.view)` however `HUD.show(.systemActivity)` dies. The shorthand way dies on line 100 (4.2.1) `let view: UIView = view ?? viewToPresentOn ?? UIApplication.shared.keyWindow!` of `PKHUD.swift`

I'm calling `.show()` on my VC's `viewDidLoad` so I'm sorta confused by this approach has worked on previous releases.

**Comment by Monte-Hansen** [comment]
+1

I also experience **fatal error: unexpectedly found nil while unwrapping an Optional value** from the root VC

**Comment by PGLongo** [comment]
Thanks @Monte-Hansen.

In the root VC  `swift UIApplication.shared.keyWindow` is nil, so you have to specify manually the view, or show the HUD in `viewDidAppear`

We can catch the error, but you will have an inconsistent behaviour.

By the way I think that you have a design problem in your app. Are you sure that the first thing that the user should see is the HUD?
