### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Srinivasulu3264** [pkluz/PKHUD#163]
open func show(onView view: UIView? = nil)
    {
        let view: UIView = view ?? viewToPresentOn ?? UIApplication.shared.keyWindow! ........ here I am getting the Above Error
        if  !view.subviews.contains(container) {
            view.addSubview(container)

plz solve this issue....

**Comment by PGLongo** [comment]
Hi, how have you call the hud? Can be a duplicate od #162
