### ISSUE TITLE
Hud.show() on specific view does not work

### ISSUE THREAD

**Issue by jacob-abraham** [pkluz/PKHUD#164]
Attempting to use Hud.show or PKHud.sharedInstance.show to show hud on a specific view, not as a content blocker. The functions does not work, it shows a hud not animating in the top right corner instead of an animating one in the center.

**Comment by PGLongo** [comment]
Please can you add some sample code?

**Comment by jacob-abraham** [comment]
HUD.show(.progress, onView: self)
    //progress
    HUD.hide()

self is a UIView subclass

**Comment by PGLongo** [comment]
Tested in the demo project and it seems correct to me. Witch version are you using?
``` swift   
  @IBAction func showAnimatedProgressHUD(_ sender: AnyObject) {
        PKHUD.sharedHUD.contentView = PKHUDProgressView()
        PKHUD.sharedHUD.show(onView: self.view)
 // or
        HUD.show(.progress, onView: self.view)
    }
```

**Comment by jacob-abraham** [comment]
Version 4.2.1. When tested in the demo project it works for me as well, but does not work within my application.

**Comment by jacob-abraham** [comment]
It appears that the problem seems to have resolved itself. My code has changed greatly since this issue was posted so it seems to have been an issue with my codes interaction with the HUD
