### ISSUE TITLE
HUD Visible State on Init

### ISSUE THREAD

**Issue by Veronique** [pkluz/PKHUD#166]
`HUD.isVisible` currently return true when the HUD even though it has never been presented.

This PR resolves the issue by setting `isHidden = true` in `Window.swift` when it is initialized:
https://github.com/pkluz/PKHUD/pull/165

This issue became visible when I was implementing deeplinking in my app. I only want to proceed with a deep link if there is no non-interruptible operation in process, easily identified by the HUD being visible.

**Comment by PGLongo** [comment]
Hi @Veronique, thanks for the catch and the PR

**Comment by PGLongo** [comment]
Merged

**Comment by Veronique** [comment]
Thanks for looking at it so quickly. Can you tell me when you will release a new version? Thanks.

**Comment by PGLongo** [comment]
I try to release a minor version today.

**Comment by PGLongo** [comment]
Done
<img width="582" alt="screen shot 2017-05-10 at 23 40 22" src="https://cloud.githubusercontent.com/assets/3647884/25938320/172553ae-362f-11e7-8ae8-4a6115192415.png">

**Comment by Veronique** [comment]
Thank you for doing this so quickly.
It would be helpful if you indicated in the release what the change is.

**Comment by PGLongo** [comment]
If you look ad the picture is the 4.2.2 ;)

**Comment by Veronique** [comment]
I was referring to the release notes:
https://github.com/pkluz/PKHUD/releases
