### ISSUE TITLE
Assertion failure [xcode 9]

### ISSUE THREAD

**Issue by sacred0x01** [pkluz/PKHUD#171]
Just built project with xcode 9 and  after
` PKHUD.sharedHUD.contentView = PKHUDProgressView()`
got 

> *** Assertion failure in -[PKHUD.FrameView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3678.13/UIVisualEffectView.m:1364

**Comment by vhbit** [comment]
Fixed in #172

**Comment by PGLongo** [comment]
Fixed via #169
