### ISSUE TITLE
Xcode 9 Compatibility Issue (add subviews to visual effect view)

### ISSUE THREAD

**Issue by StephenClarkApps** [pkluz/PKHUD#173]
Output:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<PKHUD.PKHUDErrorView: 0x1054c8df0; frame = (0 0; 156 156); clipsToBounds = YES; alpha = 0.85; layer = <CALayer: 0x1c0435e00>> has been added as a subview to <PKHUD.FrameView: 0x1056d9a70; baseClass = UIVisualEffectView; frame = (0 0; 156 156); clipsToBounds = YES; autoresize = LM+RM+TM+BM; layer = <CALayer: 0x1c40394e0>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

**Comment by StephenClarkApps** [comment]
Fix looks correct in "Fix add subview to UIVisualEffectView" pull request, may need some conditional logic to choose old / new code by iOS version ???

**Comment by PGLongo** [comment]
Fixed via #169
