### ISSUE TITLE
How to show an error using HUD, if HUD.progress takes too long?

### ISSUE THREAD

**Issue by feliciaf** [pkluz/PKHUD#176]
Hi,

Was wondering if HUD.show progress can have a time limit whereas if it passes more than 1 minute, to show a HUD.show subtitle: "error" with an error image? Please need guidance. Would really appreciate it. (using swift 2.0, Xcode 7.3.1) thanks

**Comment by PGLongo** [comment]
Hi @feliciaf. If you want to ask some questions, please use Stackoverflow with the tag 'pkhud' (read [here](https://github.com/pkluz/PKHUD#communication-hat-tip-alamofire) for more details).

By the way you can achieve your goal using a [Timer](https://developer.apple.com/documentation/foundation/timer).

```swift
func showError(){
        HUD.flash(.error)
     }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        Timer.scheduledTimer(timeInterval: 60, target: self, selector: #selector(DemoViewController.showError), userInfo: nil, repeats: false)
    }  
```

Probably you are running a task in background, if yes you should remember to invalidate the timer if the task ends before 60 seconds and to stop the task if the timer is fired

**Comment by feliciaf** [comment]
ok thanks for that @PGLongo
