### ISSUE TITLE
Keep HUD under inputAccessoryView

### ISSUE THREAD

**Issue by timqzm** [pkluz/PKHUD#177]
Is there a way to keep HUD under inputAccessoryView?
![2017-06-29 10 55 21](https://user-images.githubusercontent.com/13407092/27677287-bbea631a-5cb9-11e7-9f51-6014cb5b51df.jpg)

**Comment by PGLongo** [comment]
This is not an issue but a questione. Please [read here](https://github.com/pkluz/PKHUD#communication-hat-tip-alamofire).

**Comment by timqzm** [comment]
@PGLongo sorry, I can't create a question at SO with pkhud tag:

![screen shot 2017-06-30 at 09 32 37](https://user-images.githubusercontent.com/13407092/27723746-335cd474-5d77-11e7-83e7-fec3fb7253ce.png)

**Comment by PGLongo** [comment]
Ok, create a question without a tag and post also here the link.

**Comment by timqzm** [comment]
@PGLongo https://stackoverflow.com/questions/44840460/ios-keep-pkhud-under-inputaccessoryview

**Comment by timqzm** [comment]
thanks 👍

**Comment by timqzm** [comment]
@PGLongo now keyboard covers HUD :( I've created [gist](gist.github.com/timqzm/df7f462f12d6efd9070a19c72a52f932)  with pic, have a look please
