### ISSUE TITLE
Cannot load underlying module for 'PKHUD'

### ISSUE THREAD

**Issue by shengyangyu** [pkluz/PKHUD#178]
when i get code from pod, import PKHUD error.version info:Installing PKHUD 4.2.3 (was 4.2.1)

**Comment by shengyangyu** [comment]
sorry， i am clean projetc is ok，but why i am create new project will happen same error

**Comment by josharnoldjosh** [comment]
I had the same issue. Run 'pod update' and update all your pods. That fixed it for me.
