### ISSUE TITLE
Xcode 9 beta 3 build issue

### ISSUE THREAD

**Issue by Babelfisch** [pkluz/PKHUD#182]
I got three errors in lines 59, 129, and 164 of `PKHUD.swift`:

```
Argument of '#selector' refers to instance method 'willEnterForeground' that is not exposed to Objective-C
Add '@objc' to expose this instance method to Objective-C [Fix]
```

I tried to set Swift Language Version to 3.2 for the Pods but without effect.

**Comment by PGLongo** [comment]
You should use the swift4 branch
