### ISSUE TITLE
Swift4 build issue

### ISSUE THREAD

**Issue by DennisSzymanski** [pkluz/PKHUD#185]
In the current Swift4 branch there is an error when compiling ->  line 80 in HUD.swift
"case .progress():
            return PKHUDProgressView()"

Removing the brackets (case .progess:) fixed the error.

**Comment by luzianscherrer** [comment]
Same issue. Quick fix as mentioned by @DennisSzymanski did work, thanks.

**Comment by PGLongo** [comment]
You should use the swift4 branch

**Comment by luzianscherrer** [comment]
Wait a second, the issue **is** in the swift4 branch.

**Comment by PGLongo** [comment]
It was only a warning by the way I've updated the project to the last Xcode beta version and fixed your problem
