### ISSUE TITLE
HELP: How can I show a custom spinner in progress HUD

### ISSUE THREAD

**Issue by HerrWurstwasser** [pkluz/PKHUD#188]
Hi,

I want to show a custom spinner in progress HUD which should rotate. I this possible? And how can I implement this?

Thank you for helping me out with this,
HerrWurstwasser

**Comment by PGLongo** [comment]
Have a look to this: [https://github.com/pkluz/PKHUD/wiki/FAQ#can-i-cutomize-huds-frame-and-how](FAQ).

You can easily add your custom HUD
