### ISSUE TITLE
Do not add subviews directly to the visual effect view itself

### ISSUE THREAD

**Issue by milligator** [pkluz/PKHUD#190]
Hi,

Running my project on Xcode 9, I faced an issue.
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<PKHUD.PKHUDProgressView: 0x7ffa91c23be0; frame = (0 0; 156 156); clipsToBounds = YES; alpha = 0.85; layer = <CALayer: 0x600000421e80>> has been added as a subview to <PKHUD.FrameView: 0x7ffa91c55ed0; baseClass = UIVisualEffectView; frame = (0 0; 156 156); clipsToBounds = YES; autoresize = LM+RM+TM+BM; layer = <CALayer: 0x604000626120>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

Br,

**Comment by piotrdenis** [comment]
iOS11? in FrameView.swift, in  internal var content: UIView {....} change:

addSubview(_content)

to 

self.contentView.addSubview(_content)

:)

**Comment by PGLongo** [comment]
Use the swift4 branch
