### ISSUE TITLE
iOS 11 crash

### ISSUE THREAD

**Issue by romacv** [pkluz/PKHUD#200]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<PKHUD.PKHUDProgressView: 0x149e6c470; frame = (0 0; 156 156); clipsToBounds = YES; alpha = 0.85; layer = <CALayer: 0x1c04276c0>> has been added as a subview to <PKHUD.FrameView: 0x149e6a210; baseClass = UIVisualEffectView; frame = (0 0; 156 156); clipsToBounds = YES; autoresize = LM+RM+TM+BM; layer = <CALayer: 0x1c0426aa0>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

**Comment by PGLongo** [comment]
Use the swift4 release

`  pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'
`
