### ISSUE TITLE
FrameView makes crash the app

### ISSUE THREAD

**Issue by xxZap** [pkluz/PKHUD#202]
I'm working with Xcode 9.0 and my app crashes everytime I use the lib with:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<PKHUD.PKHUDProgressView: 0x7f91c75ec010; frame = (0 0; 156 156); clipsToBounds = YES; alpha = 0.85; layer = <CALayer: 0x600000a266a0>> has been added as a subview to <PKHUD.FrameView: 0x7f91c75e9860; baseClass = UIVisualEffectView; frame = (0 0; 156 156); clipsToBounds = YES; autoresize = LM+RM+TM+BM; layer = <CALayer: 0x600000a255c0>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

when:
`contentView.addSubview(_content)`

inside **FrameView.swift:**
`internal var content: UIView { set }`

I haven't seen this exception before.
I tried both the swift3 and swift4 versions of the pod

The stacktree is:
`FrameView.content.setter`
`PKHUD.contentView.setter`
`static HUD.show(:onView:)`

**Comment by PGLongo** [comment]
Try again the swift4 branch release, because this issue has been fixed
