### ISSUE TITLE
Swift 4 Compiler Error

### ISSUE THREAD

**Issue by laohanme** [pkluz/PKHUD#203]
<img width="263" alt="screen shot 2017-09-28 at 1 29 02 pm" src="https://user-images.githubusercontent.com/18119268/30950729-57177dda-a451-11e7-8b92-20a4b0d037e0.png">

**Comment by johnalanwoods** [comment]
Issue persists on current version.

Simple fix to remove the parenthesis after the .progress case.

**Comment by PGLongo** [comment]
@laohanme you should use the release/swift4

`
pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'
`

**Comment by laohanme** [comment]
Thanks for the answer

**Comment by PGLongo** [comment]
You are welcome. As soon I fix the issue with Objc I will release a new pod version
