### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by flyOfYW** [pkluz/PKHUD#211]
Daniel: Hello, I now use the open source swift project in the bomb box prompt, but I found the bomb box and some tips, the picture is too large, giving the user a feeling a bit rough, you do not know whether the latter intends to optimize

**Comment by PGLongo** [comment]
In english please

**Comment by PGLongo** [comment]
At the moment is not possible to change default HUD's frame. But you can easily create your own HUD, as described in the [Wiki](https://github.com/pkluz/PKHUD/wiki/FAQ#can-i-cutomize-huds-frame-and-how)
