### ISSUE TITLE
Updated Readme 

### ISSUE THREAD

**Issue by justdan0227** [pkluz/PKHUD#222]
Can we get an updated readme that explains the differences between .flash and .show and how to set titles and messages for each?  Thanks!

**Comment by PGLongo** [comment]
It's already written: 

> Now, you can proceed to show an arbitrary HUD (and have it automatically disappear a second later) like this:

**Comment by justdan0227** [comment]
Hey PGLongo, there is nothing after the "like this:" in your comment.  Was there a link?  Thanks

**Comment by PGLongo** [comment]
@justdan0227 I've copied a little part of the [README](https://github.com/pkluz/PKHUD#how-to])
