### ISSUE TITLE
Cannot compile under Xcode 6.3 beta 3

### ISSUE THREAD

**Issue by piercifani** [pkluz/PKHUD#23]
Hello, it seems like the compiler is complaining about missing the NSCoder parameter in the init method in Xcode's latest beta. Is this something you're planning to fix or do you need a hand with it? All the best!

**Comment by pkluz** [comment]
This lib is compatible with the latest stable / released version of xcode. It is not beta-ware. Once 6.3 ships, an update will be available. Feel free to provide a PR with the appropriate fixes and I'll merge it onto a development branch.

**Comment by pkluz** [comment]
Closed.
