### ISSUE TITLE
Swift 4.2 errors

### ISSUE THREAD

**Issue by TheFlow95** [pkluz/PKHUD#238]
There are several errors in your project in Swift 4.2 so I cannot build my app… Can you fix them? Here are the errors :
* `commonModes` has been renamed to `RunLoop.Mode.common`
* `init(activityIndicatorStyle:)` has been renamed to `init(style:)`

**EDIT:**
There is also the following warning:

    `let` properties are implicitly `final`; use `public` instead of `open`

**Comment by ChildrenGreens** [comment]
@TheFlow95 Me too, I hope to resolve it as soon as possible.

**Comment by robelsh** [comment]
Need to wait for a new release [PR](https://github.com/pkluz/PKHUD/pull/233)

**Comment by isaiasmac** [comment]
I have the same problem.

**Comment by kmiloaguilar** [comment]
I think this might be something that the pod is not getting the proper files because in the master branch the changes required are in place.

**Comment by kmiloaguilar** [comment]
Something temporal, but `pod 'PKHUD', :git => 'git@github.com:pkluz/PKHUD.git'` works.

**Comment by isaiasmac** [comment]
I get this message: 

[!] Error installing PKHUD
[!] Failed to download 'PKHUD'.

**Comment by PGLongo** [comment]
Check out the new release
