### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by PGLongo** [pkluz/PKHUD#24]
Hi @pkluz,

the project contains a podspec file but the I cannot find the project on CocoaPods. Do you know the reason?

**Comment by pkluz** [comment]
CocoaPods 0.36 has only recently been released, and I haven’t yet had the time to submit the spec.
Until then I recommend using it as follows:

`pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :tag => '1.0.0'`

**Comment by PGLongo** [comment]
Ok, thanks

**Comment by tbaranes** [comment]
Thanks for the tips, I'm using it this way so far. Do you think to add the projet in CocoaPods in future?

**Comment by htarwara6245** [comment]
If i am going to add this library from cocoapods,what do i need to do.
Thanks
Beautiful library that u got

**Comment by androidcn** [comment]
pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :tag => '1.0.0'

can support new version?

**Comment by rajohns08** [comment]
There are still no cocoapods install instructions in README

**Comment by pkluz** [comment]
Resolved as of 2.2.1.
