### ISSUE TITLE
Problem with CoreMotion causes UI API called on a background thread, IPhone X series

### ISSUE THREAD

**Issue by hackerpex** [pkluz/PKHUD#251]
this problem just block presentation on ios 12x only int IPhone X series

this part of code was commented and solve the problem

//        let motionEffectsX = UIInterpolatingMotionEffect(keyPath: "center.x", type: .tiltAlongHorizontalAxis)
//        motionEffectsX.maximumRelativeValue = offset
//        motionEffectsX.minimumRelativeValue = -offset
//
//        let motionEffectsY = UIInterpolatingMotionEffect(keyPath: "center.y", type: .tiltAlongVerticalAxis)
//        motionEffectsY.maximumRelativeValue = offset
//        motionEffectsY.minimumRelativeValue = -offset

//        let group = UIMotionEffectGroup()
//        group.motionEffects = [motionEffectsX, motionEffectsY]
//
//        addMotionEffect(group)

**Comment by tarekeg** [comment]
thanks a lot

**Comment by stefanrenne** [comment]
Wrapping that piece of code with a dispatch async also solve

`
        DispatchQueue.main.async {
            let motionEffectsX = UIInterpolatingMotionEffect(keyPath: "center.x", type: .tiltAlongHorizontalAxis)
            motionEffectsX.maximumRelativeValue = offset
            motionEffectsX.minimumRelativeValue = -offset
            
            let motionEffectsY = UIInterpolatingMotionEffect(keyPath: "center.y", type: .tiltAlongVerticalAxis)
            motionEffectsY.maximumRelativeValue = offset
            motionEffectsY.minimumRelativeValue = -offset
            
            let group = UIMotionEffectGroup()
            group.motionEffects = [motionEffectsX, motionEffectsY]
            
            self.addMotionEffect(group)
        }
`

**Comment by PGLongo** [comment]
merged the pr

**Comment by jbmaxwell** [comment]
I'm running 5.2.1 and still get this error. Is it not merged?

**Comment by jbmaxwell** [comment]
Updated my project to Xcode 10.2, Swift 5, cloned your repo and updated PKHUD to 5.2.2, and same Main Thread Checker error.
