### ISSUE TITLE
Issue with XCODE 6.2 and Framework installation

### ISSUE THREAD

**Issue by cwoloszynski** [pkluz/PKHUD#27]
First, thanks for a great framework!

I am using Xcode 6.2 and adding this to a Swift-based app project.

I have included the Xcode project from a git clone today as a sub-project in my main project.  Then I added in the framework to my project.  So far so good.  

I can run the app in the simulator. 

But when I try to run the app on a real device, I get:

dyld: Library not loaded: @rpath/PKHUD.framework/PKHUD
  Referenced from: /private/var/mobile/Containers/Bundle/Application/ED9F903F-610B-4955-AE35-C306FA088868/Jeeves.app/Jeeves
  Reason: image not found
(lldb) 

Any ideas on the reason for this?

**Comment by pkluz** [comment]
This error might be because you are not code-signing the framework, which is required as of iOS 8.
I.e. the framework targets you import you have to code sign as well.

**Comment by androidcn** [comment]
how to add the framework to my project?
i'm a swift programing beginner
