### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by waltermvp** [pkluz/PKHUD#29]
Any chance this is coming?

**Comment by wallance** [comment]
+1 for this request.

**Comment by istx25** [comment]
Already works..

**Comment by coanag** [comment]
I use carthage but when try to archive i get error:
PKHUD.framework/PKHUD was built without full bitcode. All frameworks and delis for bitcode must be generated from Xcode Archive or Install build for architecture arm64

Any workarounds?

**Comment by istx25** [comment]
I received the same error with another project. I would suggest either turning off Bitcode on your project entirely or to search your build settings for "User defined" and add an entry called `STRIP_BITCODE_FROM_COPIED_FILES` and set the value to `NO`. Hope this works! :dancer:

**Comment by coanag** [comment]
I confirm it,
I've changed in project build settings
Enable Bitcode -> false
BITCODE_GENERATION_MODE -> bitcode
and passed the validation.

**Comment by pangpingfei** [comment]
＋111111111111

**Comment by ramunasjurgilas** [comment]
+1

**Comment by istx25** [comment]
Carthage is already supported. It's just bitcode which is causing problems. Easy to disable as discussed above.

**Comment by pangpingfei** [comment]
@istx25 bitcode is so necessary

**Comment by PGLongo** [comment]
PKHUD support Carthage. I've just tested id

**Comment by jquiambao** [comment]
setting STRIP_BITCODE_FROM_COPIED_FILES to NO did not work for me.

**Comment by istx25** [comment]
@jquiambao: afaik, Bitcode is now a requirement/will result in a rejection (but I could be wrong).

**Comment by PGLongo** [comment]
@jquiambao as I said before PKHUD support Carthage. So if you have any trouble please provide more details.

**Comment by jquiambao** [comment]
> @jquiambao as I said before PKHUD supports Carthage. So if you have any trouble please provide more details.

Yes, I'm able to use it with my project. However, I'm getting bitcode error same as @coanag above. I tried what @istx25 suggested, but it did not work for me.

Has anybody got bitcode working with this?

**Comment by istx25** [comment]
A few general things I'll recommend:

If you're going to try to use it without Bitcode:

- Ensure the `STRIP_BITCODE_FROM_COPIED_FILES` is set to `YES` and clear your derived data (`File > Workspace Settings`). And then try again.
- Also try submitting to the app store using Application Loader instead of directly inside the organizer.

If that doesn't work, follow-up and I'll reach out to some contacts about Bitcode and try to figure out how to use Bitcode although off hand, I'm not sure. I'm also going to retract my statement about Bitcode being required now as I couldn't find any info supporting that after I posted it (although I may still be incorrect either way).

**Comment by istx25** [comment]
I'd also appreciate it if you'd share screenshots of the error(s) you're seeing in addition to an Xcode project that reproduces the issue in a simple set so I can test myself.

**Comment by istx25** [comment]
Feel free to email me at willow.puge@realm.io if you can't share a project publicly. I don't mind taking a look at it tomorrow when I have some free time. :-)

**Comment by PGLongo** [comment]
> Yes, I'm able to use it with my project. However, I'm getting bitcode error same as @coanag above. I tried what @istx25 suggested, but it did not work for me.
Has anybody got bitcode working with this?

So is it a problem related to Carthage and not to PKHUD?

Anyway if you provide some details or the screen of the error maybe someone can help you.
