### ISSUE TITLE
New release for Xcode6.3 & cocoapods?

### ISSUE THREAD

**Issue by newbdez33** [pkluz/PKHUD#32]

**Comment by thedamfr** [comment]
Latest Pod is not compiling in Xcode 6.3

**Comment by thedamfr** [comment]
Using pod from git is a valid workaround :
```
pod 'PKHUD', :git => "https://github.com/pkluz/PKHUD.git"
```

**Comment by tbaranes** [comment]
Any news about a future update?

**Comment by danyalaytekin** [comment]
Bump :)

@pkluz

**Comment by dmyers** [comment]
:+1:

**Comment by borut-t** [comment]
+1

**Comment by ayushgoel** [comment]
Any news for a future bump up?
https://github.com/pkluz/PKHUD/issues/32#issuecomment-97021458 seems to work till then..
