### ISSUE TITLE
README needs update

### ISSUE THREAD

**Issue by xissburg** [pkluz/PKHUD#33]
The API changed and the README still reflects the old API usage.

**Comment by germanger** [comment]
How is the new usage? I guess its something like `PKHUD.sharedHUD.something.something`?

**Comment by germanger** [comment]
If it helps someone:

The README now says this:

        var contentView = HUDContentView.ProgressView()
        HUDController.sharedController.contentView = contentView
        HUDController.sharedController.show()

And the way to achieve that today is this:

        var contentView = PKHUDProgressView()
        PKHUD.sharedHUD.contentView = contentView
        PKHUD.sharedHUD.show()

So, for the rest of the examples: you get the idea.

**Comment by ctews** [comment]
Thx @germanger for the hint, was just a lil bit confused. To save devs sanity an upgrade of the readme would be very appreciated!

**Comment by androidcn** [comment]
add cocoapods readme

**Comment by dmyers** [comment]
:+1:

**Comment by ayushgoel** [comment]
+1

**Comment by pkluz** [comment]
Resolved as of 2.2.1
