### ISSUE TITLE
Old Progress Image Asset Please

### ISSUE THREAD

**Issue by Jayvd** [pkluz/PKHUD#34]
Hello, the old progress asset is really cool. Is it possible you could provide the vector version of it? *.pdf

Thanks for providing such a great framework!!
![progress 2x](https://cloud.githubusercontent.com/assets/10528643/7729303/3f7f2ec6-ff3e-11e4-8dea-17e0c9cb9f3e.png)

**Comment by pkluz** [comment]
Available in `PKHUDAssets` as `progressCircularImage`.
