### ISSUE TITLE
"for IOS 8": it wont run in IOS 7?

### ISSUE THREAD

**Issue by germanger** [pkluz/PKHUD#35]
I know it says "for IOS 8" twice, but... will it run in IOS 7?

If the answer is yes: do you recommend using CocoaSeeds?
If the answer is no: do you recommend a similar library?

**Comment by pkluz** [comment]
It won't run on iOS 7 because iOS 7 doesn't provide a `UIVisualEffectsView` (the blur view). Unfortunately I cannot recommend other libraries as I didn't look into any.

**Comment by germanger** [comment]
Thanks.

Offtopic: if you didn't look into any for IOS 7, you don't care at all giving support to IOS 7? I'm currently in this dilemma.

**Comment by pkluz** [comment]
Sorry not planning on supporting iOS 7 as the entire point of this library (i.e. an exact copy of Apple's implementation) wouldn't be easily achievable.
