### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by Fight** [pkluz/PKHUD#42]
NSForwarding: warning: object 0x17404b610 of class 'PKHUD.PKHUD' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[PKHUD.PKHUD hideAnimated]

**Comment by johnbushnell** [comment]
If you make the main class a subclass of NSObject this bug goes away. I've tested it locally. I don't know if it's the right solution though.
