### ISSUE TITLE
Error encountered in Xcode 6.4

### ISSUE THREAD

**Issue by gregoryjose** [pkluz/PKHUD#43]
Pods/PKHUD/PKHUD/PKHUDContentView.swift:132:30: Initializer does not override a designated initializer from its superclass

Pods/PKHUD/PKHUD/PKHUDContentView.swift:38:19: Missing argument for parameter 'coder' in call

Pods/PKHUD/PKHUD/PKHUDContentView.swift:73:19: Missing argument for parameter 'coder' in call

Pods/PKHUD/PKHUD/Window.swift:69:39: Missing argument label 'completion:' in call

**Comment by pkluz** [comment]
Resolved as of Xcode 7.0 and release 2.2.1
