### ISSUE TITLE
iOS 8 error in latest version

### ISSUE THREAD

**Issue by coanag** [pkluz/PKHUD#47]
When switching to deployment target 8.0 i get error:
Module file's minimum deployment target is ios9.0 v9.0: PKHUD.framework/Modules/PKHUD.swiftmodule/x86_64.swiftmodule

Any suggesting to work both in 8 & 9?

Thanks in advance

**Comment by pkluz** [comment]
Confirmed, fix imminent.

**Comment by pkluz** [comment]
Should be resolved as of three days ago. Poke me if not.
