### ISSUE TITLE
Status bar bug?

### ISSUE THREAD

**Issue by istx25** [pkluz/PKHUD#48]
Hey!

I'm using `PKHUD` to present a brief dialog to inform them of a feature, but for some reason when `PKHUD` displays the hud, the status bar changes from `.LightContent` to `.Default`. Anyway to correct this so it stays white?

My current code:

```swift
PKHUD.sharedHUD.contentView = PKHUDTextView(text: "Text")
PKHUD.sharedHUD.dimsBackground = false
PKHUD.sharedHUD.show()
PKHUD.sharedHUD.hide(afterDelay: 2.0)
```

I would appreciate any help!

**Comment by pkluz** [comment]
looking into it

**Comment by istx25** [comment]
Any luck?

**Comment by istx25** [comment]
Any luck?

**Comment by pkluz** [comment]
Confirmed. There's certain scenarios - specifically it seems when the `rootViewController` is swapped at any point, that cause this bug to occur.

**Comment by hebertialmeida** [comment]
Same for me. 

This is happening because PKHUD uses rootViewController StatusBar, so if you are not in Root and your VC has a different statusBar it will uses from root, not previous VC.

**Comment by pkluz** [comment]
Quite possible resolved now

**Comment by fitch** [comment]
I'm still experiencing this with PKHUD (3.2.1).

**Comment by Laptopmini** [comment]
This is still a bug in PKHUD (4.0)
