### ISSUE TITLE
Unrecognized selector setInitialVelocity:

### ISSUE THREAD

**Issue by NicosKaralis** [pkluz/PKHUD#49]
Trying to display an error view using the default `PKHUDErrorView` I got this error:

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CASpringAnimation setInitialVelocity:]: unrecognized selector sent to instance 0x170621f40'

More especifically `-[PKHUDErrorView springyRotationAnimation:]` at `animation.initialVelocity = 0.5`

I'm using cocoa pods and xcode 7.0.1

**Comment by pkluz** [comment]
What iOS version are you deploying to?

**Comment by NicosKaralis** [comment]
XCode Deployment 8.0
Device iOS 8.3

**Comment by allewun** [comment]
It's been [fixed](https://github.com/pkluz/PKHUD/commit/b5180a1e5ac7fb00f0700b8832d7ccaff591fa95).

**Comment by JLGB** [comment]
How do you solve
