### ISSUE TITLE
Title on Error or Success

### ISSUE THREAD

**Issue by benjaminhallock** [pkluz/PKHUD#53]
This is a nice extension, but I find it painfully difficult to use.

Not sure how swift works, but I don't want to type `sharedHud`

I would like it to work more like this https://github.com/relatedcode/ProgressHUD

It should be `PKHUD.show("String")` then `PKHUD.success`

And at least give me a chance to put a title in the error for god sakes.

**Comment by flandy84** [comment]
+1 for this nice  HUD! 

+2 when you add a title property to the delivered hud-variants (error, success, progress...etc.)

**Comment by pkluz** [comment]
@benjaminhallock The primary aim of this extension is to provide a _basis_ for your own customizations. There's an extensive set of base classes that you can do anything with. I cannot possibly provide every single variant, so I give you the lego pieces.

I'll consider a class interface for the `sharedHUD` and try to provide a more extensive title'ing interface for the animated error / success views.

Remember: You're always welcome to submit a PR adding these extensions right here - upstream.

**Comment by liamscofield** [comment]
it seems good for adding this feature

**Comment by PGLongo** [comment]
@pkluz  maybe we could add *titleLabel* and *subtitleLabel* to **PKHUDSquareBaseView**

**Comment by Flar49** [comment]
@benjaminhallock 
> This is a nice extension, but I find it painfully difficult to use.
> Not sure how swift works, but I don't want to type sharedHud

Usability issues are addressed in the following PR:  #69

**Comment by benjaminhallock** [comment]
@Flar49 Hey thanks!

**Comment by ADevelopStudio** [comment]
Also waiting for adding title and subtitle to Error and Success! 
All the rest is fine. but now have to use DoneHUD :(

**Comment by PGLongo** [comment]
@ADevelopStudio you have to wait because it's a little bit complicated. This functionality has been introduced in this PR #67, but it require a new pod version and @pkluz has to review the code before the merge.

If you can't wait you can always set the pod url to my fork, until the merge.

**Comment by pkluz** [comment]
This feature has now been added.
