### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by maddoggy1979** [pkluz/PKHUD#64]
I've installed using Cocoapods, and my app written in swift.
Everything works fine in the simulator but when loading on a device, it crashes with the following error.

```
dyld: Library not loaded: @rpath/PKHUD.framework/PKHUD
  Referenced from: /var/mobile/Containers/Bundle/Application/457898E0-D0D7-4733-AE87-3AA67134785A/forexer.app/forexer
  Reason: image not found
```

I've tried adding the framework to the 'copy bundle resources' but that doesn't even build.

Any suggestions?

**Comment by pkluz** [comment]
Not a PKHUD relates error. Please consult [CocoaPods Issue #3661](https://github.com/CocoaPods/CocoaPods/issues/3661).
