### ISSUE TITLE
PKHUDStatusProgressView not found!

### ISSUE THREAD

**Issue by webleandroromano** [pkluz/PKHUD#65]
I imported the PKHUD for my project using CocoaPods and PKHUDStatusProgressView.Swift file was not found.

Can you fix that? Thanks!

**Comment by PGLongo** [comment]
Please can you post your pod configuration?

**Comment by webleandroromano** [comment]
target 'myProject' do

pod "PKHUD"

use_frameworks!

end

**Comment by PGLongo** [comment]
@pkluz din't submit the new version containing PKHUDStatusProgressView to Cocoapods.

**Comment by webleandroromano** [comment]
Exactly!

The alternative worked perfectly.
How do I upgrade my project with your alternative?

**Comment by PGLongo** [comment]
Setting you pod in this way

```
platform :ios, "8.0"
use_frameworks!

target 'myProject' do
   pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git'
end
```

**Comment by webleandroromano** [comment]
**Perfect, thanks!**
