### ISSUE TITLE
CocoaPods Release

### ISSUE THREAD

**Issue by kimar** [pkluz/PKHUD#7]
Would be awesome to see a CocoaPods release of this lib, as soon as CocoaPods (officially) supports Swift libraries.
http://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by ararog** [comment]
+1

**Comment by pkluz** [comment]
See #4. Being worked on.

**Comment by pkluz** [comment]
Resolved. Added and tagged the first version as 1.0.0.
