### ISSUE TITLE
HUD.hide(afterDelay: completion:) doesn't call completion

### ISSUE THREAD

**Issue by mitrenegade** [pkluz/PKHUD#74]
Tracing through a debug, it seems that the userInfo that contains the completion block is nil after the delay.

The code I used (replacing the demo code):

    @IBAction func showTextHUD(sender: AnyObject) {
        HUD.show(.Label("Text."))
        HUD.hide(afterDelay: 2, completion: { (complete) -> Void in
            print("here")
        })
    }

**Comment by pkluz** [comment]
Thanks for reporting this! Fixed already :)
