### ISSUE TITLE
how i can control the alpha for the hud background 

### ISSUE THREAD

**Issue by ahmedsafadii** [pkluz/PKHUD#75]
for example i did a progress animation , i want make alpha for the background of progress 

![screen shot 2016-02-29 at 7 45 32 pm](https://cloud.githubusercontent.com/assets/6974081/13404002/5d883f8a-df20-11e5-8678-f49f06284129.png)

how i can control ?

**Comment by PGLongo** [comment]
This is not an issue but a simple question. You should use other platforms like StackOverflow

By the way you can control the background of the HUD or of the contentView as following.

```swift
PKHUD.sharedHUD.contentView.backgroundColor = YOUR_COLOR
// Remove the HUD background
PKHUD.sharedHUD.dimsBackground = false
```

And you can easily achieve something like this

![simulator screen shot 01 mar 2016 20 52 49](https://cloud.githubusercontent.com/assets/3647884/13439875/b3daf696-dfef-11e5-8765-cf95cd0b7150.png)
![simulator screen shot 01 mar 2016 20 52 40](https://cloud.githubusercontent.com/assets/3647884/13439873/b3c38e98-dfef-11e5-919a-d417325c8cbe.png)
![simulator screen shot 01 mar 2016 20 52 28](https://cloud.githubusercontent.com/assets/3647884/13439874/b3d1b964-dfef-11e5-8fec-8ce769c0a3f5.png)

**Comment by ahmedsafadii** [comment]
i meant the progress background to be alpha , not my view

**Comment by PGLongo** [comment]
The _progress_activity_ is an image with **Render as** set to Default so you can't change the properties of that image. You can provide your image and change the imageView.image like

```swift
let progressView = PKHUDProgressView()
self.progressView.imageView.image = YOUR_IMAGE
```

@pkluz maybe would be better to add a constructor for custom images and set **Render as** to Template.

**Comment by ahmedsafadii** [comment]
i will try that ;)

**Comment by VMavrin** [comment]
How to get absolutely transparent HUD?

Now I should do this dummed code:
```
PKHUD.sharedHUD.contentView = PKHUDRotatingImageView(image: UIImage(asset: .Preloader))
PKHUD.sharedHUD.contentView.superview?.backgroundColor = UIColor.clearColor()
for view in (PKHUD.sharedHUD.contentView.superview?.subviews)! {
       view.backgroundColor = UIColor.clearColor()
}
PKHUD.sharedHUD.dimsBackground = false
PKHUD.sharedHUD.show()
```

**Comment by ahmedsafadii** [comment]
PKHUD.sharedHUD.contentView = PKHUDRotatingImageView(image: UIImage(asset: .Preloader))


image: UIImage(asset: .Progress))

 Type of expression is ambiguous without more context

**Comment by pmbfish40** [comment]
PKHUD.sharedHUD.contentView = PKHUDRotatingImageView(image: UIImage(named: "ic_loader"))
PKHUD.sharedHUD.contentView.backgroundColor = UIColor.clear
PKHUD.sharedHUD.dimsBackground = false
PKHUD.sharedHUD.show()

Clear color not working here. Is there any other way to hide dimsbackground?

**Comment by shashijangir** [comment]
Clear color problem here also.
IOS 11 -  xcode 9

**Comment by ian123nai321** [comment]
try codes below
       

>  PKHUD.sharedHUD.contentView = CustomView()
>         PKHUD.sharedHUD.contentView.backgroundColor = .clear
>         PKHUD.sharedHUD.effect = nil
>         PKHUD.sharedHUD.dimsBackground = false
>         PKHUD.sharedHUD.show()

above codes are my clear background Color Solution!

**Comment by Speakus** [comment]
There is no any way from this thread which work properly with current version of library unfortunately :(

**Comment by MaxWeaver** [comment]
PKHUD.sharedHUD.effect = nil
        if let frameView = PKHUD.sharedHUD.contentView.superview?.superview as? UIVisualEffectView {
            frameView.backgroundColor = nil
        }
