### ISSUE TITLE
Compatible with Obj-C?

### ISSUE THREAD

**Issue by ericlewis** [pkluz/PKHUD#83]
Can this be used via bridge, if so how?

**Comment by pkluz** [comment]
Yes you can use it in Objective-C without problems (at least none I know of yet)...

Example:
```objective-c
@import PKHUD;

[PKHUD sharedHUD].contentView = [[PKHUDSuccessView alloc] init];
[[PKHUD sharedHUD] show];
```

**Comment by nestserau** [comment]
No longer the case with Swift 4.
