### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by Jiropole** [pkluz/PKHUD#85]
I see that people are getting warnings about animating opacity, but that it appears to be a non-issue. However, I'm also seeing `Unbalanced calls to begin/end appearance transitions for <PKHUD.WindowRootViewController: 0x15f819cc0>.` My usage is very simple, and I'm not changing view controllers or anything unexpected. Is anyone else seeing this? 

```
HUD.show(.LabeledProgress(title: NSLocalizedString("Please Wait", comment: "HUD title"), subtitle: nil))
```

and later,

```
HUD.hide()
```

**Comment by Sunitadaffodil** [comment]
I am also getting warning about animating opacity. In my case, it gives me warning and stops animating and disappears from the screen. And I am left with blank screen.

Any workaround to fix this issue??

**Comment by Jiropole** [comment]
@Sunitadaffodil I'd recommend going with a different library, as this one (at the time of this writing) seems a bit unstable or out of date, and largely unsupported.

**Comment by PGLongo** [comment]
@Jiropole can you give more details about your context?
