### ISSUE TITLE
App becomes unresponsive if HUD is hidden while the app is in background

### ISSUE THREAD

**Issue by iamZoltanVaradi** [pkluz/PKHUD#92]
I cloned the most up to date version of PKHUD, modified one function in DemoViewController.swift:

```
@IBAction func showAnimatedProgressHUD(sender: AnyObject) {
        HUD.show(.Progress)
        
        delay(5.0) {
            //HUD.flash(.Success, delay: 1.0)
            HUD.hide(afterDelay: 5.0)
        }
    }
```
If i press the home button while the animation is in progress and wait until i know it's hidden, when i reopen the app, the whole screen gets unresponsive.

**Comment by iamZoltanVaradi** [comment]
I cracked the issue
Window.swift's funcion called hideFrameView is responsible for it. 
The block finalized checks if animation is finished before setting
```
self.hidden = true
self.resignKeyWindow()
```
But that will never be true, if the app is in the background. So either don't check against it, or be sure to remove it another way. My hotfix solution is ugly, but working:
 ```
if finished || UIApplication.sharedApplication().applicationState == .Background {
 ...
}

```

**Comment by Sunitadaffodil** [comment]
I am also facing the same issue.

**Comment by pkluz** [comment]
Resolved via 766b1e.
