### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Tulleb** [pkluz/PKHUD#94]
Hello and thanks for this framework,

Is there a Swift 3 branch on its way?

I can't use it with Xcode 8 and Swift 3 beta and Cocoapods... Or couldn't find how to.

Thanks!

**Comment by pkluz** [comment]
Working on it right now :)

**Comment by Tulleb** [comment]
Great, thanks @pkluz!
Ask if you need any help with a PR or something.

**Comment by SanjoDeundiak** [comment]
Need it as well!

**Comment by ctews** [comment]
Would also really appreciate a Swift 3 branch! :)

**Comment by appsird** [comment]
Swift 3 and iOS10 support would be welcome

**Comment by IceFloe** [comment]
I want this swift 3 version too ) Thanks pkluz

**Comment by Tulleb** [comment]
Any news @pkluz?

**Comment by JackoPlane** [comment]
Any updates on the Swift 3 branch?

**Comment by vCrespoP** [comment]
+1 for final Xcode 8

**Comment by Tulleb** [comment]
You can use:

`pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'`

Meanwhile @pkluz merge @toyship's PR.

**Comment by alexandergmacleod** [comment]
`pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'` doesn't work for me. Still build error:

> Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by Tulleb** [comment]
@alexandergmacleod http://stackoverflow.com/a/38466703/2854405

**Comment by danipralea** [comment]
+1

**Comment by pkluz** [comment]
Resolved via `43e3ad3`
