### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by oferRounds** [pkluz/PKHUD#95]
1. Does PKHUD supports obj-c (i.e., calling it from an obj-c class)?
2. Can I customize the font?

Way to go for this really cool and beautiful library!

**Comment by pkluz** [comment]
1. Yes you can use it with Obj-C.
Simple as:
```
[[PKHUD sharedHUD] ...];
```

2. Yes. You can either provide an entirely custom content view for the HUD all together, or you can access the `titleLabel` etc. properties and change their font.

**Comment by oferRounds** [comment]
Great - thank you!

**Comment by c826** [comment]
@pkluz 
Can I cutomize HUD's frame  and how?
Sorry to that  not read code and just go here to ask you question.

And Thanks for this library

**Comment by PGLongo** [comment]
@c826 it's better to read the code or at least search for similar questions (#117). By the way I've created a Wiki with the [FAQ](https://github.com/pkluz/PKHUD/wiki/FAQ) page

**Comment by c826** [comment]
@PGLongo my situation is more complex than that, But anyway thanks for that, i'll read the code and ifx it. Thank you.

**Comment by PGLongo** [comment]
@c826 you are welcome. If your situation is more complex you should give more details. I suggest to use Stackoverflow as I've written in the [README.md](https://github.com/pkluz/PKHUD#communication-hat-tip-alamofire)
