### ISSUE TITLE
Decrease the size of .Progress view

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [pkluz/PKHUD#99]
How can I decrease the size of HUD?

**Comment by sunbohong** [comment]
I couldn't find a good way to decrease the size of HUD.
But I use follow code to solve it temporarily.
You should always check it worked correctly as `PKHUD` release new version.
```
let view = PKHUDSuccessView()
PKHUD.sharedHUD.contentView = view
view.superview!.layer.setAffineTransform( CGAffineTransformScale(CGAffineTransformIdentity, 0.5, 0.5))
```

**Comment by sunbohong** [comment]
If you use `PKHUD.sharedHUD`
You should reset after hide it.

		let view = PKHUDSuccessView()
		PKHUD.sharedHUD.contentView = view

		view.superview!.layer.setAffineTransform(CGAffineTransformScale(CGAffineTransformIdentity, 0.5, 0.5))

		PKHUD.sharedHUD.show()

		PKHUD.sharedHUD.hide(afterDelay: 1.0) { success in

			view.superview!.layer.setAffineTransform(CGAffineTransformIdentity)
		}

**Comment by PGLongo** [comment]
Please look at #117. I've answered to a similar question. 

I will think and discuss with @pkluz about exposing the size of the views
